name: Appartement Jhomarons
favicon: null
layout_spectrum: 0.3456566787790507
typography_spectrum: 0.05238857981748879
title: Appartement à louer à Morzine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2986730707343668
  lightness: 0.4338784229476005
  saturation: 0.16069335443899035
  rhythmicContrast: 0.41496599232777953
purpose: []
