name: Appartement Jhomarons
favicon: null
layout_spectrum: 0.3456566787790507
typography_spectrum: 0.05238857981748879
title: Location à Morzine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030900'
    - '#ffffff'
    - '#5079b1'
    - '#5e6c17'
    - '#3e4200'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
purpose: []
